<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Bo cp 16 vo Bin ng_wp-image-131</name>
   <tag></tag>
   <elementGuidId>0eb0c6f9-3714-4a03-a2ec-ec7758ae3418</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.wp-image-131</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-129']/div/div/div/div/div/div/div[2]/div/div/figure/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c1ba605c-12a8-4144-860b-cdfe1a5d42f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attachment-id</name>
      <type>Main</type>
      <value>131</value>
      <webElementGuid>5cf1f623-0b3a-4f7f-a62a-254f1a71d787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-permalink</name>
      <type>Main</type>
      <value>https://2051052105phuong.wordpress.com/thoi-su/attachment/115/</value>
      <webElementGuid>7e28edce-704e-400d-8dff-c36ad8c8654c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orig-file</name>
      <type>Main</type>
      <value>https://2051052105phuong.files.wordpress.com/2023/08/115.jpg</value>
      <webElementGuid>1177e139-60ec-40ab-bfab-2cff6c0ceea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orig-size</name>
      <type>Main</type>
      <value>832,499</value>
      <webElementGuid>63e27407-6ded-44c6-821e-0096a283cb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-comments-opened</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6ce0fdb9-ef42-4ae5-ae7e-4485f64e82bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-meta</name>
      <type>Main</type>
      <value>{&quot;aperture&quot;:&quot;2.4&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;iPhone X&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;1692255724&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;6&quot;,&quot;iso&quot;:&quot;16&quot;,&quot;shutter_speed&quot;:&quot;0.00093808630393996&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;1&quot;}</value>
      <webElementGuid>bd7f6ac9-9dd5-4189-8125-a695b81d6610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-title</name>
      <type>Main</type>
      <value>115</value>
      <webElementGuid>2c9464e7-d9ee-48be-8247-0c56886ae811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-medium-file</name>
      <type>Main</type>
      <value>https://2051052105phuong.files.wordpress.com/2023/08/115.jpg?w=300</value>
      <webElementGuid>abdb8d10-3c77-4be5-8e40-569755cef57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-large-file</name>
      <type>Main</type>
      <value>https://2051052105phuong.files.wordpress.com/2023/08/115.jpg?w=832</value>
      <webElementGuid>9a81ad8c-8c44-41ee-bb32-d5a2feb4d846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://2051052105phuong.files.wordpress.com/2023/08/115.jpg?w=832</value>
      <webElementGuid>a634b784-0d8b-441e-9840-ad879f113d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-image-131</value>
      <webElementGuid>8cf102b2-e031-4763-aa12-0d8869581437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://2051052105phuong.files.wordpress.com/2023/08/115.jpg 832w, https://2051052105phuong.files.wordpress.com/2023/08/115.jpg?w=150 150w, https://2051052105phuong.files.wordpress.com/2023/08/115.jpg?w=300 300w, https://2051052105phuong.files.wordpress.com/2023/08/115.jpg?w=768 768w</value>
      <webElementGuid>b34c9f3f-2801-439e-aa2a-34a94891b15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 832px) 100vw, 832px</value>
      <webElementGuid>123e8125-8b93-4d7a-b1f4-30b93e45fac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-129&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;wp-block-group alignfull has-background-color has-foreground-background-color has-text-color has-background has-link-color wp-elements-48e6ed8c4019a2f68ad018b21fd4bc96 is-layout-constrained wp-block-group-is-layout-constrained&quot;]/div[@class=&quot;wp-block-group__inner-container&quot;]/div[@class=&quot;wp-block-group alignwide is-layout-flow wp-block-group-is-layout-flow&quot;]/div[@class=&quot;wp-block-group__inner-container&quot;]/div[@class=&quot;wp-block-columns alignwide is-layout-flex wp-container-11 wp-block-columns-is-layout-flex&quot;]/div[@class=&quot;wp-block-column is-layout-flow wp-block-column-is-layout-flow&quot;]/div[@class=&quot;wp-block-group is-layout-flow wp-block-group-is-layout-flow&quot;]/div[@class=&quot;wp-block-group__inner-container&quot;]/figure[@class=&quot;wp-block-image size-large is-resized&quot;]/a[1]/img[@class=&quot;wp-image-131&quot;]</value>
      <webElementGuid>bd81a561-2ddc-47d5-90e6-bbf19961ab40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-129']/div/div/div/div/div/div/div[2]/div/div/figure/a/img</value>
      <webElementGuid>6f8a0e93-dec3-4981-bf92-3cff0c3ddfc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://2051052105phuong.files.wordpress.com/2023/08/115.jpg?w=832')]</value>
      <webElementGuid>bf42a37c-d12b-4251-b825-bba32c80339d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/figure/a/img</value>
      <webElementGuid>06f6fa6b-f2ba-4b6b-9e4f-db58408c4a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://2051052105phuong.files.wordpress.com/2023/08/115.jpg?w=832']</value>
      <webElementGuid>35e78924-9bac-4d78-bc09-5cd93eca813d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
