<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log in or provide your name and email_67afff</name>
   <tag></tag>
   <elementGuidId>13cf9042-411a-470c-b9aa-25b959d11fec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ebabbbb-9c55-41e4-9e66-f3cecd6cbc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>c0cb5ed5-154e-418f-9c80-9627563f9756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e105c2d3-5d25-4cdc-8c27-50cadccde1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>eebc667c-db88-4b2f-9a3b-3f06009c9e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e0ff1ae8-6bd0-4456-9206-c86f4fc40c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email (Address never made public)</value>
      <webElementGuid>07a8b7a4-cb65-438f-abc0-235d417d9696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>verbum-form__email </value>
      <webElementGuid>78af5d9a-6eef-41eb-a5d3-939210a9548c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comment-form__verbum&quot;)/div[@class=&quot;comment-form__subscription-options open&quot;]/div[@class=&quot;verbum-subscriptions logged-out&quot;]/div[@class=&quot;verbum-subscriptions__wrapper&quot;]/div[@class=&quot;verbum-subscriptions__login&quot;]/div[@class=&quot;verbum-form open&quot;]/div[@class=&quot;verbum-form__wrapper&quot;]/div[@class=&quot;verbum-form__content&quot;]/label[@class=&quot;verbum__label&quot;]/input[@class=&quot;verbum-form__email&quot;]</value>
      <webElementGuid>0b179e22-f3c2-4a95-81a9-2b51f1be06bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>4d071f06-86ea-4cf7-836f-f2af3b1a80bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comment-form__verbum']/div[2]/div/div/div/div[3]/div/div/label/input</value>
      <webElementGuid>1127fdfe-290d-48f4-be74-c853946621ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>eadc404b-d3e3-4271-85c6-a7fd64961422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @placeholder = 'Email (Address never made public)']</value>
      <webElementGuid>955f4398-6cdb-4926-acfa-2c09f88fd2c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
