<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log in or provide your name and email_92bd69</name>
   <tag></tag>
   <elementGuidId>961fba35-2e84-4613-a0e7-339ac442100c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;author&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='author']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1def70ce-6942-45a3-9cc3-21040627422a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6c141f0-e111-490f-abd4-d221dd8b2116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1f928d5c-fde5-41d0-8505-164c56e1cc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>c6f8d106-6363-4779-9d19-8a6f20c55def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>author</value>
      <webElementGuid>71d54874-772c-4bd8-a527-a37cda06aa34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>1e96c1ad-d730-4e4a-868b-b207f71c0ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>verbum-form__name </value>
      <webElementGuid>6c5e9ede-7c14-46a7-b6f7-fe5ccb1a279b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comment-form__verbum&quot;)/div[@class=&quot;comment-form__subscription-options open&quot;]/div[@class=&quot;verbum-subscriptions logged-out&quot;]/div[@class=&quot;verbum-subscriptions__wrapper&quot;]/div[@class=&quot;verbum-subscriptions__login&quot;]/div[@class=&quot;verbum-form open&quot;]/div[@class=&quot;verbum-form__wrapper&quot;]/div[@class=&quot;verbum-form__content&quot;]/label[@class=&quot;verbum__label&quot;]/input[@class=&quot;verbum-form__name&quot;]</value>
      <webElementGuid>b1bcf13b-3ed7-49b8-88d1-c1ccce5241f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='author']</value>
      <webElementGuid>f1bab018-4f99-46b2-b5b3-7ebbbd172c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comment-form__verbum']/div[2]/div/div/div/div[3]/div/div/label[2]/input</value>
      <webElementGuid>59bf31c4-dab0-4475-83ea-ffab3eb74298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>ee4de3d2-c7c2-4563-9572-eb44def2252d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'author' and @placeholder = 'Name']</value>
      <webElementGuid>0a1324de-ac89-411e-8a9a-e0fe014ae5a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
