<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bo him_attachment-post-thumbnail wp-post-image</name>
   <tag></tag>
   <elementGuidId>e69f84e6-8345-445e-9c1c-3d3e904de73d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-post-thumbnail.wp-post-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-157']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b1ad7463-f15a-477c-9e4f-e3534f59ae8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>9518b19b-a695-4d34-a25e-5bc9f1c01b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>1696555c-2e1e-46d0-a728-df4ae1a35d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://2051052105phuong.files.wordpress.com/2023/08/11111.jpg?w=450&amp;h=450&amp;crop=1</value>
      <webElementGuid>9f6a2808-9d75-424b-acdf-063face6eb3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>67b2efb0-68c9-4ef1-9aa7-f14c5503be66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Đóng bảo hiểm tự nguyện có thể hưởng lương hưu sớm ở tuổi 55-60</value>
      <webElementGuid>82d3a9ab-fc5f-4a15-a232-3aaa10abcecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-post-thumbnail wp-post-image</value>
      <webElementGuid>a413cb1f-d73e-4954-b96b-4fb38f419aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-157&quot;)/a[@class=&quot;entry-thumbnail apostrophe-2-thumb&quot;]/img[@class=&quot;attachment-post-thumbnail wp-post-image&quot;]</value>
      <webElementGuid>df9e039d-3651-423e-baca-93c9c93038fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-157']/a/img</value>
      <webElementGuid>8ce5ef9f-0e19-44f9-9ca7-641093a13460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Đóng bảo hiểm tự nguyện có thể hưởng lương hưu sớm ở tuổi 55-60']</value>
      <webElementGuid>24757e37-3a10-4493-ba89-a9c4f22c841a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>21e953d2-20c7-4eed-8531-b083107c98de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://2051052105phuong.files.wordpress.com/2023/08/11111.jpg?w=450&amp;h=450&amp;crop=1' and @title = 'Đóng bảo hiểm tự nguyện có thể hưởng lương hưu sớm ở tuổi 55-60']</value>
      <webElementGuid>e5d24f08-9bfa-4df6-8992-787eed116214</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
