<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tm kim_s</name>
   <tag></tag>
   <elementGuidId>29ea5a44-bf64-40f0-964f-f6d6a305d5b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wp-block-search__input-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wp-block-search__input-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e5e8de1-95db-4787-bc55-3db20d82df72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-search__input</value>
      <webElementGuid>c81e7afe-2dbe-499d-a685-8295952669c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wp-block-search__input-1</value>
      <webElementGuid>60218265-d1ca-4274-a494-432f6c15b9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b1cb849d-9536-4545-a20c-46b5a5d37e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>66255a77-d2b0-4533-bb6a-430bb4bf5841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp-block-search__input-1&quot;)</value>
      <webElementGuid>141f5673-24ed-4190-86d1-7e946c2bca90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wp-block-search__input-1']</value>
      <webElementGuid>16215af3-c973-4b81-9994-beec9225d804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-129']/div/form/div/input</value>
      <webElementGuid>a9fbc219-5ad8-4b67-9c7e-d2ae238f696c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3d51275b-bc9a-4d45-8696-c67740b8e50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'wp-block-search__input-1' and @type = 'search' and @name = 's']</value>
      <webElementGuid>6858df3f-2404-4efe-81b0-cd1ba4a9f467</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
