<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Trang ch</name>
   <tag></tag>
   <elementGuidId>2219746e-0d70-4f92-bb8b-80bfe823bfd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-28 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-28']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ecd2b8b2-98a8-4c1a-a8bb-187ac34ac01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://2051052105phuong.wordpress.com/</value>
      <webElementGuid>788c7d39-3a5e-4e6f-a4c2-ae1a42ba827f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trang chủ</value>
      <webElementGuid>68a9160d-27c1-4b60-a279-8474e0717651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-28&quot;)/a[1]</value>
      <webElementGuid>64b4ea31-6b84-44d3-bcea-21f0c7d681e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-28']/a</value>
      <webElementGuid>5f917c3a-85ba-409c-9d7c-5027373f25bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Trang chủ')]</value>
      <webElementGuid>f694511f-8ed9-4500-8f2f-4613d858dfc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to content'])[1]/following::a[1]</value>
      <webElementGuid>3b05fe8e-4c45-4628-b016-f68ac6bdf334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::a[2]</value>
      <webElementGuid>13da4b79-3f81-42b0-b142-6c950fd8221d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tin tức'])[1]/preceding::a[1]</value>
      <webElementGuid>9271adc5-ea0f-437a-9834-24010f8dc092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thời sự'])[1]/preceding::a[2]</value>
      <webElementGuid>5680b1da-7d44-45cc-9429-96c1e020da21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Trang chủ']/parent::*</value>
      <webElementGuid>3e879aab-245a-4baa-a9e9-c07bbe0548d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://2051052105phuong.wordpress.com/')])[2]</value>
      <webElementGuid>9f0d77ac-a465-40c2-bb27-fb75fb6d2be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>aee53d13-411b-47a9-9cb8-4f5f881bb861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://2051052105phuong.wordpress.com/' and (text() = 'Trang chủ' or . = 'Trang chủ')]</value>
      <webElementGuid>3d10bc51-a1ea-46b0-964b-1e2c1a32b5a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
