<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tm kim_s</name>
   <tag></tag>
   <elementGuidId>ad20641c-6efd-4694-8c5a-21d4d1a92d4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wp-block-search__input-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wp-block-search__input-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32801ab9-7080-4c02-8e87-a7d9587cdd13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-search__input</value>
      <webElementGuid>4fa97005-5ef2-490d-8eef-b34466ae49c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wp-block-search__input-1</value>
      <webElementGuid>31d29f17-3eac-4a3d-b65b-48413af565b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>86431b93-6f5d-4912-a180-6d2186700408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>cddfdc40-f9aa-4181-b0af-bc1f9d3ed925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp-block-search__input-1&quot;)</value>
      <webElementGuid>ab2a1c92-c4c3-4807-b2d1-2bf0e529a0d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wp-block-search__input-1']</value>
      <webElementGuid>412ab38f-08aa-4293-a6fe-30fe13558ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-18']/div/form/div/input</value>
      <webElementGuid>cfa7f096-3130-4321-93a0-30ebdffe1872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8f7707d5-b62e-4841-b4de-6a4487d072c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'wp-block-search__input-1' and @type = 'search' and @name = 's']</value>
      <webElementGuid>2470a0d6-2e0d-47b4-8d40-f303f1e2169c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
