<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Thi s</name>
   <tag></tag>
   <elementGuidId>13578a8d-21a9-413a-b6f9-c788b7fc369c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-139 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-139']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54b40e84-d164-4dcf-a3c1-1612586654cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://2051052105phuong.wordpress.com/thoi-su/</value>
      <webElementGuid>36b254ec-9d9c-4668-b3ea-24abfa01aa1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thời sự</value>
      <webElementGuid>25401c70-6721-4a71-82dd-8a65977d8a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-139&quot;)/a[1]</value>
      <webElementGuid>57d7942b-ee4f-4dd9-8974-a4c7cfbd43af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-139']/a</value>
      <webElementGuid>35c07535-5120-4871-9218-08162e5e7a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Thời sự')]</value>
      <webElementGuid>699dcb68-95ee-45c0-8bb7-5bc973416544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tin tức'])[1]/following::a[1]</value>
      <webElementGuid>397d1004-3dfc-471d-af66-1d1eab8eca22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[1]/following::a[2]</value>
      <webElementGuid>aa3cd931-bd23-4609-b249-8cf190412414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thế giới'])[1]/preceding::a[1]</value>
      <webElementGuid>570f59f5-1f98-4e10-9ac6-f52ff0add95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Du lịch'])[1]/preceding::a[2]</value>
      <webElementGuid>dbe442d9-b84f-4756-9199-48b71b57a51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thời sự']/parent::*</value>
      <webElementGuid>d3f1d8f1-859c-4fe8-861f-d6e0228c2370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://2051052105phuong.wordpress.com/thoi-su/')]</value>
      <webElementGuid>e432ba5f-1371-4a83-907b-24763e6eb4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>26513e79-ccdc-4b19-9595-4b74c6266c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://2051052105phuong.wordpress.com/thoi-su/' and (text() = 'Thời sự' or . = 'Thời sự')]</value>
      <webElementGuid>83a4dff2-4dc0-4c3b-a481-522cd727f46a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
